# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '1'

services:
  relayer1:
    container_name: relayer1
    build:
      context: ../.
    command: run --config /cfg/config.json --fresh
    volumes:
      - ./cfg:/cfg
      - ./certs:/certs
    restart: always

  relayer2:
    container_name: relayer2
    build:
      context: ../.
    command: run --config /cfg/config.json --fresh
    volumes:
      - ./cfg:/cfg
      - ./certs:/certs
    restart: always

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./cfg/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8889:8889"   # Prometheus exporter metrics
