# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only
version: '3'

services:


  relayer2:
    container_name: relayer2
    build:
      context: ../../.
      dockerfile: Dockerfile
    command: run --config /cfg/config_evm-evm1.json --testkey bob --fresh
    volumes:
      - ./example/cfg:/cfg
    restart: always


